#!/usr/bin/env sh
# vim: fen

VERSION=0.7.0
PROGNAME="$(basename $0)"

CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}"
DATA="${XDG_DATA_HOME:-$HOME/.local/share}"
QUITERSS="QuiteRss"

BACKUP_FILENAME="quiterss-backup"
BACKUP_FILEEXT=".tar.gz"
BACKUP_DEF_FILE="$BACKUP_FILENAME$BACKUP_FILEEXT"

usage() {
    echo "Usage: "$PROGNAME" [options] [file]"
    echo
    echo "Options:"
    echo "    * no option *      Creates '$BACKUP_FILENAME_<DATE>$BACKUP_FILEEXT' backup file"
    echo "    -h, --help         Shows this help"
    echo "    -v, --version      Prints version number"
    echo "    -b, --backup       Creates '$BACKUP_DEF_FILE' backup file"
    echo "    -c, --custom-name  Creates backup file with user defined filename"
    echo "    -r, --restore      Restores from '$BACKUP_DEF_FILE' or from given file path"
}

backup() {
    BACKUP_FILE="$1"
    command tar -czP --transform "s,^$CONFIG,config," --transform "s,^$DATA,data," \
        --exclude=*backup* \
        -f "$BACKUP_FILE" \
        "$CONFIG/$QUITERSS" "$DATA/$QUITERSS"
}

unarchive() {
    mkdir -p "$3"
    command tar -C "$3" --strip-components 1 -xzf "$1" "$2/$QUITERSS"
}

restore() {
    unarchive "$1" config "$CONFIG"
    unarchive "$1" data   "$DATA"
}

case "$1" in
    '')
        backup "./$BACKUP_FILENAME_$(command date +"%Y%m%d-%H%M%S")$BACKUP_FILEEXT"
        ;;
    -h|--help)
        usage
        ;;
    -v|--version)
        echo $VERSION
        ;;
    -b|--backup)
        backup "./$BACKUP_DEF_FILE"
        ;;
    -c|--custom-name)
        if [ -n "$2" ]; then
            backup "$2"
        else
            echo "Please provide the custom name of backup file" 1>&2
        fi
        ;;
    -r|--restore)
        if [ -z "$2" ]; then
            if [ -e "./$BACKUP_DEF_FILE" ]; then
                restore "./$BACKUP_DEF_FILE"
            else
                echo "Please provide the path to backup file" 1>&2
            fi
        else
            if [ -e "$2" ]; then
                restore "$2"
            else
                echo " $2  - file doesn't exist" 1>&2
            fi
        fi
        ;;
    *)
        echo " $1 - no such option" 1>&2
        ;;
esac
