#!/bin/bash

VERSION=0.6.3
PROGNAME="$(basename $0)"

usage() {
    echo "Usage: "$PROGNAME" [options] [file]"
    echo
    echo "Options:"
    echo "    * no option *      Creates 'quiterss-backup_<DATE>.tar.gz' backup file"
    echo "    -h, --help         Show this help"
    echo "    -v, --version      Print version number"
    echo "    -b, --backup       Creates 'quiterss-backup.tar.gz' backup file"
    echo "    -c, --custom-name  Creates backup file with user defined filename"
    echo "    -r, --restore      Restores from 'quiterss-backup.tar.gz' or from given file path"
}

CONFIG="${XDG_CONFIG_HOME:-.config}/QuiteRss"
CONFIG="${CONFIG#"$HOME/"}"
DATA="${XDG_DATA_HOME:-.local/share}/QuiteRss"
DATA="${DATA#"$HOME/"}"

case "$1" in
    '')
        command tar -czf ./quiterss-backup_$(command date +"%Y%m%d-%H%M%S").tar.gz -C "$HOME" "$CONFIG" "$DATA"
        ;;
    -h|--help)
        usage
        ;;
    -v|--version)
        echo $VERSION
        ;;
    -b|--backup)
        command tar -czf ./quiterss-backup.tar.gz -C "$HOME" "$CONFIG" "$DATA"
        ;;
    -c|--custom-name)
        command tar -czf "./$2.tar.gz" "$CONFIG" "$DATA"
        ;;
    -r|--restore)
        if [ -z "$2" ]; then
            if [ -e ./quiterss-backup.tar.gz ]; then
                command tar -xzf ./quiterss-backup.tar.gz -C $HOME
            else
                echo "Please provide the path to backup file"
            fi
        else
            if [ -e $2 ]; then
                command tar -xzf $2 -C $HOME
            else
                echo " $2  - file doesn't exist"
            fi
        fi
        ;;
    *)
        echo " $1 - no such option"
        ;;
esac
